
server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
#        defaultZone: http://springdemo-946701722.cn-northwest-1.elb.amazonaws.com.cn/eureka/
        defaultZone: http://eureka.copilot001.local:8761/eureka/
zuul:
  routes:
    provider: /provider/**