version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mylayer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1all7f4idgwz5"
s3_prefix = "mylayer"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
