AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Dependencylayer02

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  ServerlessSaaSLayers02:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: authdependency02
      Description: Utilities for project
      ContentUri: layers/
      CompatibleRuntimes:
        - python3.8          
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain      
    Metadata:
      BuildMethod: python3.8 