version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lj95e6exkuhw"
s3_prefix = "sam-app-2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"simplechat_connections\""
